### ISSUE TITLE
Shipping labels: "State" dropdown shows countries.

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4387]
When I tap to select a state in the shipping labels creation flow, instead of seeing a list of American states I see a list of countries.

![state](https://user-images.githubusercontent.com/3903757/124982304-8ae9c800-e004-11eb-9406-52055be870c0.png)

If that list of countries is used elsewhere, it looks like we need to escape the country names.

![amp](https://user-images.githubusercontent.com/3903757/124982406-a81e9680-e004-11eb-8cc6-117adf9f2b8b.png)

**Comment by nbradbury** [comment]
@hichamboushaba I wonder if we want to move the Country field above the State field, so the country is more likely to be filled in before selecting a state? Because right now it really should enforce requiring a country before selecting a state.

**Comment by hichamboushaba** [comment]
I totally missed this ticket.

> When I tap to select a state in the shipping labels creation flow, instead of seeing a list of American states I see a list of countries.

Do you have some exact steps on how to reproduce this? I can't reproduce it on my device.

> If that list of countries is used elsewhere, it looks like we need to escape the country names.

I'll look into that.

> @hichamboushaba I wonder if we want to move the Country field above the State field, so the country is more likely to be filled in before selecting a state? Because right now it really should enforce requiring a country before selecting a state.

yes, I think it should be better to have the country first, as we change the state's field from an edit text to a spinner depending on the country. @Garance91540 WDYT?

**Comment by nbradbury** [comment]
> Do you have some exact steps on how to reproduce this? I can't reproduce it on my device.

I can reproduce it by _not_ selecting a country before selecting a state. When I first ran into this, though, the country was set to US (but I can't reproduce that now).

**Comment by hichamboushaba** [comment]
> I can reproduce it by not selecting a country before selecting a state. When I first ran into this, though, the country was set to US (but I can't reproduce that now).

So maybe it was fixed by the last PR #4401.
I'll try to have a small PR to fix the other point about unescaping the country names, and I'll handle the order of fields change separately once we Garance's feedback.

Thanks for raising this @nbradbury

**Comment by Garance91540** [comment]
> yes, I think it should be better to have the country first, as we change the state's field from an edit text to a spinner depending on the country. @Garance91540 WDYT?

Yes country first makes sense! But as a bunch of countries don't have states (including France), I'm wondering if changing the state's field from edit text to spinner is a good idea. In the case of France, what would be the states options?

**Comment by hichamboushaba** [comment]
> Yes country first makes sense! But as a bunch of countries don't have states (including France), I'm wondering if changing the state's field from edit text to spinner is a good idea. In the case of France, what would be the states options?

We are following the same pattern as WCShip, when the state field is an edit text, it becomes optional.
But to improve the UX, I think we should rename the field's title to something like "State / County", similar to what Woo Core does for the shipping address, as it would make it more clear that the user can enter the state name, or a region/province/county... WDYT about this @Garance91540 ?

**Comment by Garance91540** [comment]
> the user can enter the state name, or a region/province/county... WDYT about this @Garance91540 ?

That still won't apply to France for example (there's never a region/province/county field in addresses form), but yes it might be slightly better so let's do this!
