### ISSUE TITLE
[Order Creation] Retain state of "Percentage fee" checkbox when editing a fee

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5973]
Discussed in p1646250815730879-slack-C02KUCFCSFP. 

https://user-images.githubusercontent.com/198826/156442515-95c94ae1-1509-44b3-ac2f-32f45a9b53f0.mov

## Steps

1. Tapped on Fee to add a fee.
2. Checked Percentage fee.
3. Entered 10 (percentage)
4. Pressed Done.
5. Tapped on Fee to edit that fee.
6. The Percentage fee checkbox is not checked. It's showing me the Amount instead of the percentage that I entered.

## Discussion

This seems like a limitation since we save the fixed amount even if they entered a percentage. There's no easy way to tell if they previously entered a percentage. Core also behaves similarly. 

We could probably use `meta` to keep the state.

**Comment by nbradbury** [comment]
@shiki  I'm not seeing a way to retain whether it's a percentage, other than to save a value in the `ViewModel.ViewState` which tells us it's a percentage. But that's really not ideal since that information isn't available the next time they view the order.

Perhaps instead we should resolve this with a UI change? One possibility is to remove the "Percentage fee" switch from the "Add fee screen," add a button which says "Calculate from %" (or something along those lines), and when the user taps that they get a dialog asking for a percentage. When they return to the "Add fee" screen, it only shows the amount calculated from the percentage.

Or simply do as core does and enable entering either a percent or an amount in the "Add fee" screen and only show the amount on the create order form (as we do already). We'd again dump the "Percentage fee" switch in this case, which I'm in favor of because it's the "problem child" in this screen.

**Comment by shiki** [comment]
I have no better suggestion. 😅 It's a technical limitation so a UI change sounds plausible. Perhaps @joe-keenan and @adamzelinski have some inputs. 

I'm also not sure if this is important to solve. Or we can just leave it be.

**Comment by ghost** [comment]
@nbradbury @shiki in the designs we actually show the fee types using a segmented controller with $ and % with their own input fields like so. Would updating the design to match this solve the problem or will the same issue persist?

<img width="1362" alt="Screen Shot 2022-03-18 at 11 26 52 am" src="https://user-images.githubusercontent.com/74938219/158914894-e8d7c142-e8b4-43ab-af00-61ee72d2823b.png">

**Comment by nbradbury** [comment]
@adamzelinski I think that would lead to the same problem, because if they entered a percentage it would be shown as an amount when they return to that screen.

As @shiki said, this isn't a very important issue, so perhaps we can just leave it on the backburner for now?

**Comment by joe-keenan** [comment]
Until we can overcome the technical issue, the only thing I can think of is adding some clarification.
- Change “Percentage fee” to “Calculate as a percentage”
- Add a caption to the field: “Calculated amount: $23.99”

You’ll enter the percentage, see the dollar value, and confirm your decision. Then on the order details screen, you’ll recognise the dollar value when you see it again.

Is that possible?

**Comment by atorresveiga** [comment]
Based on your last comment @joe-keenan, I have updated the screen and have these 3 versions of the screen

| Plain text  | Bold value | Integrated value |
| ------------- | ------------- | ------------- |
| ![Screenshot_20220401_114017](https://user-images.githubusercontent.com/18119390/161287523-e50fb7d0-7bff-4421-8ddd-25e9ee303472.png) | ![Screenshot_20220401_113800](https://user-images.githubusercontent.com/18119390/161287841-190c1005-659f-4272-9aa4-2cf80932f865.png) | ![Screenshot_20220401_114341](https://user-images.githubusercontent.com/18119390/161288194-423e4ee5-6725-4121-8acb-1b50fe5ebefc.png) |

WDYT?

**Comment by ghost** [comment]
thanks for looking into this @atorresveiga I think the bold value is the best solution so happy to go with that.
